### ISSUE TITLE
Are these intended to be used outside of the COS?

### ISSUE THREAD

**Issue by larslevie** [CenterForOpenScience/helm-charts#14]
My Helm installation came with the `cos` repo by default, but kube can't pull the images because of a lack of permissions.

> Failed to pull image "gcr.io/cos-containers/cerebro:0.6.5": rpc error: code = Unknown desc = Error response from daemon: denied: Permission denied for "0.6.5" from request "/v2/cos-containers/cerebro/manifests/0.6.5".

I assume that the Google Container Registry is locked down, but I thought it was worth asking.

**Comment by binoculars** [comment]
@larslevie Yes, we intend for these charts to usable outside of COS. Normally, we push public images to quay, but it looks like the default for this one didn't get changed. We'll take care of that. Our GCR repo is only to ensure that the images are pulled quickly, so they're just a mirror of quay.

**Comment by larslevie** [comment]
Cool. Thanks for the info. I'll close this issue.
