### ISSUE TITLE
Url for charts repository

### ISSUE THREAD

**Issue by caulagi** [CenterForOpenScience/helm-charts#20]
The instructions provided in README under `#configuring-the-charts-repository` doesn't point to a valid charts repo. Specifically, https://centerforopenscience.github.io/helm-charts/ gives me 404. Is there a hosted charts repository I can use? Thanks.

**Comment by binoculars** [comment]
Valid charts repo just needs an index.yaml in it. https://centerforopenscience.github.io/helm-charts/index.yaml. If you follow the `help repo add` instructions, it should work.

**Comment by caulagi** [comment]
Oops, I missed checking for index.yaml and only tried the url in a browser. Works like the readme says 🤦‍♂️
